import type { Metadata } from 'next'
import { Inter, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Drawer from '@/components/Drawer'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })
const jetBrains_Mono = JetBrains_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="synthwave">
        <body className={jetBrains_Mono.className}>
          <Navbar />
          <Drawer />
          <div className="drawer-content">
            <div className="flex justify-center">
              <div className="max-w-5xl w-full">
                {children}
              </div>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>

  )
}
